export const GET_SHIPMENTS = "GET_SHIPMENTS"
export const SHIPMENT_ERROR = "SHIPMENT_ERROR"
export const GET_COUNTERS = "GET_COUNTERS"
export const SET_FILTERS = "SET_FILTERS"
export const GET_SELECTED = "GET_SELECTED"
export const SELECT_DEFAULT="SELECT_DEFAULT"
export const S="S"
export const T="T"